name: sshr-action
description: ssh remote proxy
author: Mike Chirico, https://mchirico.github.io/
inputs:
  ngrok_token:
    description: 'ngrok token'
    required: true
  vscode_port:
    description: 'vscode port'
    required: true
  id_rsa_root:
    description: 'rsa private key, to replace root'
    required: true
  authorized_keys:
    description: 'rsa public key to add to authorized_keys'
    required: true
  ssh_config:
    description: '.ssh/config'
    required: true
  code_server_password:
    description: 'vscode-server password'
    required: true
  wait_duration:
    description: '1hr'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
