
name: Sample

on:
  push:
    branches: [ pickYourBranch ]
  pull_request:
    branches: [ pickYourBranch ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    # This goes at the end
    - uses: mchirico/sshr-action@v1
      with:
        ngrok_token: ${{ secrets.NGROK_TOKEN }}
        vscode_port: 8779
        wait_duration: 17m
        id_rsa_root: ${{ secrets.ID_RSA_ROOT }}
        authorized_keys: ${{ secrets.AUTHORIZED_KEYS }}
        ssh_config: ${{ secrets.SSH_CONFIG }}
